minVersion: 0.0.1
github:
  owner: getsentry
  repo: infra-event-notifier
changelogPolicy: auto
preReleaseCommand: bash ./scripts/bump-version.sh
releaseBranchPrefix: release
targets:
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
