name: CI
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  linting:
    name: "Run linters"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      max-parallel: 3
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: actions/setup-python@v5
        name: Setup Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run linter
        run: |
          make venv
          make lint

  typing:
    name: "Type checking"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      max-parallel: 3
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: actions/setup-python@v5
        name: Setup Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run mypy
        run: |
          make venv
          make typecheck

  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: actions/setup-python@v5
        name: Setup Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          make venv
          make test
